VisualMeaning/sheet-to-triples

transforms/he_int_markers.py

Markers for HE Internal Map

---

transforms/he_int_stories.py

Attempt 1 - think I've got the names right

Tiles to stories

---

transforms/he_int_markers.py

Changed to 'Text Markers'. Haven't yet populated sheet.

Change of sheet name

---

transforms/he_int_markers.py

The thing we did to get markers to stories

Removing reference duplication

---

sheet_to_triples/field.py
transforms/he_int_markers.py

Names are not unique, so include the Story column too.
Also generate better slugs.

Improve HE markers transform and slug

---

sheet_to_triples/trans.py
transforms/eco_movements.py

Then reaggregate to same kind of form as before for now.
Also add the categories that are present in the map.

Disaggregate economic movements

---

sheet_to_triples/field.py
sheet_to_triples/rdf.py
sheet_to_triples/trans.py
sheet_to_triples/xl.py
transforms/he_group.py

Basic schema for one of the new pieces of work for HE. Various bits still to work out on design and shape.
Support for text fields that must exist.
Stop on empty spreadsheet rows.

New VMHE prefix and transform for Group items

---

sheet_to_triples/field.py
sheet_to_triples/rdf.py
sheet_to_triples/xl.py
transforms/he_group.py
transforms/he_org.py
transforms/he_person.py
transforms/he_role.py

Add some FOAF bits too and more field tidying.

Transform for Person and Role content for HE

---

transforms/he_doc.py

Still making up attributes for now without thinking too much.

Add he_doc transform

---

transforms/eco_stories.py
transforms/eco_storypoints.py

Sizing tweak by @jjeezy to adapt to story panel taking space.

Tweak frame for eco stories

---

transforms/he_views.py

Plain views with nothing too fancy for now.

Views for HE base model

---

sheet_to_triples/__main__.py

Can make interface cleaner in the future.

Poke in method of loading an existing graph

---

sheet_to_triples/field.py
transforms/mgsbr_points.py
transforms/mgsbr_stakeholders.py
transforms/mgsbr_views.py

Not in final form, but enough to show to ask questions.
Also leak capital types into field transforms for simplicity.

Transforms for MGS stakeholders and pain/bright

---

transforms/ecov_movements.py
transforms/ecov_stories.py

Create all contents from the transform an omit most story contents.

Add variant of economic system transforms

---

transforms/mgsbr_views.py

Not the ultimate answer but will do while experimenting.

Add layer names as comment to view

---

pyproject.toml
sheet_to_triples/field.py
sheet_to_triples/run.py
sheet_to_triples/xl.py
sheet_to_triples/xls.py
sheet_to_triples/xlsx.py

Add dependency on openpyxl to read .xlsx files locally.
Rearrange book loading interfaces to accomodate differences.

Support loading xlsx books locally

---

sheet_to_triples/field.py
transforms/he_delivery_partner.py
transforms/he_it_system.py

Also Delivery Partner. First pass, not all properties included yet.

Add transforms for HE IT System

---

sheet_to_triples/trans.py
transforms/he_class_icons.py

Also allow lets to be unspecified in a transform.

Add icons for classes used in HE map

---

transforms/he_delivery_partner.py
transforms/he_it_system.py
transforms/hwx_views.py

Just organisational view for now, also stub comment for identifying
layer, and no filters specified yet.

Start of views specific to HE core map

---

transforms/hwx_views.py

Updated views for HE

---

README.md
sheet_to_triples/__main__.py
sheet_to_triples/rdf.py

Moral of this story is that I should test changes to core code by running the full Highways transforms because that provides a fairly comprehensive workout of all the core behaviour.
(Or code in some unittests. But that comes later.)

Adding --spec broke some things, this fixes them.

---

sheet_to_triples/field.py
sheet_to_triples/run.py
transforms/lmru_stakeholders.py

Model with names and descriptions in two languages.
Tweak json serialisation to not escape non-ascii characters.

First pass transform for LM Russia

---

transforms/he/he_activity_type.py
transforms/he/he_data_asset.py
transforms/he/he_itsystem.py

Also tweak itsystem transform to better match target properties.
The source data for some of this is very incomplete, hence the large amount of commented out code. This is getting the transforms side of things to a place where we can ingest *something*, and quickly add other properties as and when they become available.

Add transforms for data asset and activity type.

---

transforms/ris3_views.py

To have more added by @jjeezy as we go.

First view for RIS 3 map

---

transforms/hwx_views.py

Switch to dict to label row cells.
New org version, so give version per view.

Update HE views for latest changes

---

sheet_to_triples/field.py

Let field properties cast to string where needed but still support
exception raising for empty cells.

Better handling for string field values

---

transforms/he/he_activity_type.py
transforms/he/he_capability.py
transforms/he/he_capability2activity.py
transforms/he/he_data_asset.py
transforms/he/he_itsystem.py
transforms/he/he_itsystem2activity.py
transforms/he/he_orgunit2activity.py
transforms/he/he_perfmeasures.py
transforms/he/he_project.py
transforms/he/he_project2activity.py
transforms/he_class_icons.py
transforms/hwx_views.py

Quite a bit of confusion about which classes have an HE/ component
within the iri, some do, some don't. Make all classes from the HE
ontology consistent.

Align class iris with ontology content

---

transforms/he/he_activity_type.py
transforms/hwx_views.py

Use updated activity type sheet. Things still not all linked though?
Get closer to tile background colour. Still distinguishable on my
monitor though, might be a colourspace issue.

Random end of Thursday HE model tweaks

---

transforms/he/he_data_asset.py
transforms/he/he_itsystem.py
transforms/he/he_itsystem2activity.py

Probably this kind of version-only edit is fine, but most useful when columns have changed, not just data?

Just version bumps of HE data files

---

sheet_to_triples/field.py
transforms/lmru_painpoints.py
transforms/lmru_stakeholders.py

Couple of iterations at this, and the translations are not yet actually finalised, but proposing as shipped.
Also a few quality of life adjustments, some aliases for capital types and whitespace stripping of geo fields.

Painpoint transform and updates for LM

---

transforms/mgs_stakeholders.py
transforms/mgs_views.py
transforms/mgsru_points.py

Views and stakeholders are common across regions, painpoints are
per-region so rename and create new transform for Russia.
Move towards Semantic Arts style IRIs with leading underscores for
individuals.
Remove tile overlays for stakeholder views temporarily.

Updates for MGS transforms using two regions

---

transforms/lmru_painpoints.py
transforms/lmru_stakeholders.py

Also make everything that should be a stakeholder again.

LM transforms back to multilanguage form

---

sheet_to_triples/field.py

Allows the field to be empty while still stripping non-significant
whitespace.

Add _literal helper in field

---

sheet_to_triples/__main__.py
sheet_to_triples/run.py

Avoids exceptions when --add-graph is supplied but --model is not.

Make Runner responsible for setting model terms

---

transforms/mgs_stakeholders.py
transforms/mgs_views.py
transforms/mgsbr_points.py
transforms/mgsru_points.py

Use latest copies of data, bump version, and bring back overlay tiles.

More MGS transforms updates

---

README.md
sheet_to_triples/trans.py

This is step one. Step two is set up another repo with our transforms, step three is remove the transforms from this one.

Set transforms directory via environment variable.

---

.github/workflows/gate.yml
sheet_to_triples/field.py
sheet_to_triples/tests/test_field.py

Start with the easy stuff. Started out by testing the private functions so that I could not make the method tests quite so comprehensive, but realised that's the wrong way to do it -- private functions are extensions of the method code that happen to be repeatable, and so their code outcomes should be tested as part of the method tests.

Add unittests for fields.py, also add test step into gating.

---

Makefile
sheet_to_triples/tests/test_trans.py
sheet_to_triples/trans.py

There's a couple of stub tests for query behaviour which I'm not quite sure how to test, otherwise pretty good coverage. Also rewrote a method slightly to not always assume `lets` would be present.

Add transform tests + extremely basic makefile

---

.github/workflows/gate.yml
.gitignore
Makefile
pyproject.toml

Of somewhat academic interest right now, but good to strive towards a long-term goal of 100% coverage and associated gating check.

Add code coverage + corresponding Makefile command

---

sheet_to_triples/tests/test_run.py

100% coverage, but at what cost?

Add unittests for run.py

---

sheet_to_triples/tests/test_rdf.py

Pretend this doesn't have the transforms unittests in it that went up in a separate PR.
The date on my linux VM seems to have gotten screwed up which means the transform commit has the wrong datetime on it. Guess I get to find out if that's going to be an issue for git.

Unittests for rdf module

---

sheet_to_triples/rdf.py

Some highways literal data was falling on to this path incorrectly
having both colon and spaced slashes. Adjust conditionals to avoid
unlikely content of this sort and comment to make logic clearer.

Better checked and documented sequence path

---

pyproject.toml
sheet_to_triples/__main__.py
sheet_to_triples/rdf.py
sheet_to_triples/run.py
sheet_to_triples/tests/test_main.py
sheet_to_triples/tests/test_run.py

Needed to do the duplicates dropping and sorting logic.
Do basic sort of triples when replacing from current graph.
Also update tests to use fake filesystem rather than mocking small
pieces of the os module.
Tweak wording on comment about dropped triples.

Normalise the model after adding from graph

---

sheet_to_triples/field.py
sheet_to_triples/tests/test_field.py
sheet_to_triples/tests/test_xl.py
sheet_to_triples/xlsx.py

Tests are horrible, but at least sane in their structure.

Convert ASCII carriage returns in xlsx files to `\r`

---

sheet_to_triples/field.py
sheet_to_triples/rdf.py

Includes a logic-related change for must_exist so falsey cell values
which stringify to non-empty values will raise.

Whitespace related logic cleanups

---

sheet_to_triples/rdf.py
sheet_to_triples/tests/test_rdf.py

Amount of indent has semantic meaning for markdown and such like.

Leave line-leading whitespace more alone on norm

---

sheet_to_triples/run.py

In order to get this filterset thingy working we need to be able to pass multiple filterset objects to `useFilters`, so it needs to be set as non unique in here.

Make useFilters a nonunique predicate

---

requirements.txt
sheet_to_triples/read_csv.py
sheet_to_triples/xl.py

- Update requirements.txt
- Support loading data from csv files. Created Book and Cell class wrapper to present common interface with xlsx files.

Support input sheet of csv format

---

README.md

Document the sheet_encoding transform option

---

sheet_to_triples/__main__.py

Makes it possible to catch errors including incorrect sheet format.

Include runner creation under debug flag

---

sheet_to_triples/rdf.py
sheet_to_triples/tests/test_rdf.py

When loading from a json model, there is logic to detect languages encoded onto object literals. This does not remove the json level encoding but duplicates it, so on serialisation as ttl for example results in multiple tags. Instead strip the value on load, and on serialisation to json reapply the json form.
There is some slightly magical logic outside of rdf conventions here where encoding a language for javascript array and object values, required for labels in multiple languages.

Refine behaviour of literals with lang tags

---

sheet_to_triples/field.py
sheet_to_triples/tests/test_field.py

New field method to do one-way transformation of data.
Pair change between @swhitla and I - we may end up not doing the hashing at this level for the case we were looking at as it also needs to change further upstream in the data, but the idea is fine anyway?

Added as_hash method
