sheet_to_triples/__main__.py, sheet_to_triples/field.py, sheet_to_triples/rdf.py, sheet_to_triples/run.py, transforms/mgsbr_points.py, transforms/mgsbr_views.py
Make brightspots a distinct type from painpoints.
Add some (slightly messy) support for deriving type info in field.
Support rewriting IRIs using owl:sameAs as a marker.
Drive purging behaviour from new --purge-except argument.
=> Changes for brightspot schema migration

.github/workflows/gate.yml
Upstream issue:
https://github.com/python-poetry/poetry/issues/3199
Also bump Python version in CI to same as my local copy.
=> Try workaround for spurious CI failure on install

transforms/he/he_capability.py, transforms/he/he_capability2activity.py, transforms/he/he_itsystem.py, transforms/he/he_itsystem2activity.py, transforms/he/he_orgunit.py, transforms/he/he_orgunit2activity.py, transforms/he/he_person.py, transforms/he/he_project.py, transforms/he/he_project2activity.py, transforms/hwx_views.py
* I have tried to match the ontology as closely as possible, including stub values where no values exist in the source sheets.
* This pulls its data from five different workbooks, a situation that is only going to get worse as more classes are added. The relevant workbook is noted at the top of each transform. 
* The command to build the triples is extremely fun:
```python3 -m sheet_to_triples --book '../books/highways_SMP_ingest_20210310.xlsx' --book '../books/20210310 activity2project v2.xlsx' --book '../books/20210305 org_unit2activity - master.xlsx' --book '../books/20210311 activity2itsystem v3.xlsx' --book '../books/capability2activity.xlsx' --add-graph ../turtle.owl --model ../he_empty.json hwx_labels hwx_org_labels he_class_icons hwx_views he/he_orgunit he/he_orgunit2activity …
```
=> Add HE transforms for capability, itsystem, orgunit, project, person

sheet_to_triples/__main__.py, sheet_to_triples/rdf.py, sheet_to_triples/run.py, sheet_to_triples/trans.py
This got hacky as a consequence of the way the code is currently structured, along with my knowing just enough about `argparse` to be dangerous.
* Multiple linking is achieved by adding a new `non_unique` property to a transform, which is a list of predicates. This list is propagated up and attached to the model, with new `non_unique` attributes being added with each transform. At the `normalise_model` step, any predicates in this list are deduped according to a unique combination of `subj, pred, obj` instead of `subj, pred`.
* Meanwhile I have been wrestling with a dataset that requires me to extract data from four different tabs in the source book. Ordinarily this would require adding four different transforms, which quickly becomes a logistical nightmare as we deal with more workbooks …
=> Add multiple linking for predicates and multiple transforms in 1 file

sheet_to_triples/rdf.py, sheet_to_triples/run.py, sheet_to_triples/trans.py, transforms/he/he_capability2activity.py, transforms/he/he_itsystem.py, transforms/he/he_itsystem2activity.py, transforms/he/he_orgunit2activity.py, transforms/he/he_project2activity.py
Rework how the information about predicates that can appear multiple
times gets passed around. Avoids putting it on model, which is the
external interface, and instead track on the runner.
Mark some HE transform predicates as non_unique.
=> Change and use new non_unique transform option

sheet_to_triples/xl.py
Small change fixing a constant irritation: when headers in transforms are incorrect or misspelled, the process just fails out without saying what those headers are. When you're running six transforms at once figuring out which one is going wrong without that information is a process of trial and error, so include the missing headers in the error message.
=> Surface missing headers in error message

README.md, sheet_to_triples/trans.py, transforms/he/he_capability2activity.py, transforms/he/he_itsystem.py
To supersede a hack required for HE transforms due to optional links
specified in columns. A subject must still exist (no blank nodes)
however the transform is allowed to continue if a triple lacking a
subject would have been created.
Move iri creation inline for two transforms where those triples are
optional, to be more explicit about that property.
=> Add allow_empty_subject option for transforms

README.md, sheet_to_triples/run.py, sheet_to_triples/trans.py, sheet_to_triples/xl.py, transforms/he/he_orgunit2activity.py
Split it out from `allow_empty_subject` because they're not really the same thing and I deplore having a fuzzy higher-level option which no fine control.
The `_skip_empty_rows` spelling on the transform property bugs me but I'm not sure how else to do this with `__slots__`.
=> Add `skip_empty_rows` option to transforms

transforms/he/he_project2activity.py
Been looking into phantom relationships on some activities (see the blank "is enabled by" entries at https://staging.ecosystem.guide/maps/highways/activity?s=IT#HE/information-and-technology). This particular example is due to copy and pasting and not removing some prior IRI templating from the source, which means project links from activities point at nonsense IRIs and not the actual project IRIs.
=> Fix typo in project IRI that breaks links from activities

sheet_to_triples/field.py, transforms/he/he_perfmeasures.py
Previous transforms have been relatively simple. This one was definitely not. We have many ontology classes encapsulated in this sheet with a complex set of relationships that wasn't an exact match for the source data -- there are some conceptual differences and broken linkages. I am not sure this is usable as-is as none of these objects are visible or easily reachable from things that are.
I'll write up some notes tomorrow morning so that I haven't forgotten everything by the time we do the post-mortem next week (hopefully).
Other misc changes:
* There is an `as_date_or_text` property in `field` now -- this is to try and deal with a column containing mixed date formats where Excel has helpfully converted half of it to a full yyyy/mm/dd date (which is ingested as a Python datetime and …
=> Add transform spec for performance measures

sheet_to_triples/xlsx.py
Some tweaks, which may or may not be spelled correctly:
* Cast values to string before doing string operations
* Check that an IRI for the current object can be constructed before trying to build the triple and ignore if not -- this avoids junk data in the columns used to build the IRI breaking the transform. We should at least have enough data in a row to construct a thing's IRI -- if we do not, it is not a valid thing.
* `data_only=True` on opening `.xlsx` files - my assumption here is that we do not care about Excel formulas and are merely interested in the data values within a workbook. Should probably make a matching change for `xls` files.
=> Various tweaks to transformation functions

transforms/he_class_icons.py
Turns out none of the classes in the ontology have the `HE` namespace.
=> Fix incorrect type links and add icons for DesiredResult and OrgUnit

transforms/he/he_perfmeasures.py
Spent forever trying to figure out why this link wasn't working, only to discover that I hadn't actually changed the IRI to match the IRI generated by the labels export.
This should now correctly go RecordedMeasure <- Performance Measure -> Imperative.
=> Fix IRI for the link to DesiredResult

sheet_to_triples/__main__.py
The number of workbooks involved in the HE transforms is becoming unmanageably large when you have to explicitly state the filepath for each one every time you run `sheet_to_triples`. Allowing `--book` to take a directory path instead which it can look inside to find workbooks makes it much simpler.
This does increase the risk of collisions in sheet names as by default all books inside the target directory will be iterated through in alphabetical order until the first matching sheet is found, but I have another change coming that addresses that issue.
=> Allow `--book` to take a directory path containing workbooks

sheet_to_triples/__main__.py, sheet_to_triples/run.py, sheet_to_triples/trans.py
(I was kind of hoping I could avoid including the book-directory-parsing code here as the entire point was to isolate each feature in its own PR.)
Allow a transform to explicitly specify the workbook filename that it should pull its sheet data from. This is a necessary change as we're now using something like 12 workbooks in the HE data ingest and I would really like to eliminate the possibility of sheet name collisions, however it comes with the following drawbacks:
* Every time a new workbook version is created with updated date or version number in the workbook filename, the transform also needs to be updated, which is more maintenance overhead. However I was logging the workbook names in comments to keep track of them all anyway so in reality it's not actually more work.
* My …
=> Transforms may now specify the workbook to pull sheet data from

sheet_to_triples/__main__.py, sheet_to_triples/trans.py, transforms/he/transforms_list.txt
Add `--from-list` option for reading transform names from list file.
You were right about `--spec`, having to remember which transforms are specs and which are not is too awkward, so infer it via type checking instead (even if the `yield` spelling is also very awkward).
Initially tried to add functionality to read a directory full of transforms, but this is a) surprisingly difficult and b) not precise enough, you may not want to read every transform inside the `he` directory for example. The simpler, cruder solution is actually better here: have a text file full of transform names that you can pass via `--from-list`.
With this change the insanely complicated command for running the HE transforms becomes something like:
```
python -m sheet-to-triples --add-model model.owl --book ../<synced …
```
=> Remove `--spec` and infer from file data instead.

sheet_to_triples/__main__.py, sheet_to_triples/run.py
When running a transform in multiple stages, all subsequent steps
require knowing which triples should not be sanitised out.
=> Add means to take non-unique from past transforms

transforms/he/he_perfmeasures.py
The dumbest, quickest fix for [this bug]( https://trello.com/c/QjLebeA7/237-data-collections-for-performance-measures-connected-to-imperatives-links-need-to-be-made) on the data side. Needs changes in the client to display multiple values for the same predicate for things that aren't ActivityInvolvements.
=> Add downwards link from Imperative -> Performance Measure.

transforms/he/he_activity_type.py
Pulling data from the older one was creating a bunch of broken links to activities that no longer exist.
=> Bump activity type sheet version to newest one.

sheet_to_triples/__main__.py
Useful for arbitrary global triples as well as ontology, but those should not come from the same source file.
=> Add multiple existing graphs to model

sheet_to_triples/__main__.py, sheet_to_triples/rdf.py, sheet_to_triples/run.py
For use when a first parse declares multiple identities for an
individual which a second pass needs to resolve against prior to
removing.
An input data sheet can then have old and redundant identities which
label creation can use without needing complex lookup heuristics.
=> Add flag to not resolve aliases

transforms/ris3_list.txt, transforms/ris3_risk.py
Also list of first pass RIS 3 transforms.
When map label differs, including temporary triple to show common
identity. Relationships are basically just triples already.
Note that the classes are not tied into the ontology at present.
Using convention of underscore for individuals, but no midfix yet.
=> Add RIS3 risk map data transform

sheet_to_triples/field.py
Specifying separators without whitespace.
=> More compact json output from fields

requirements.txt
Have just spent a while going through `sheet-to-triples` setup for the consultants on a Windows environment and the upshot of it is that Poetry is a no-go there - the things you need to do to get it working are far too technical, and also Windows just sucks for this stuff in general. After trying several different approaches I reverted to the most basic one possible: installing via `pip install -r requirements.txt`, which thankfully still works. 
This is something of a stopgap as we don't want to be updating two sets of requirements files every time, but does the job for now.
=> Add requirements.txt for basic install in enviroments that can't handle Poetry

sheet_to_triples/__main__.py, sheet_to_triples/trans.py
The path derivation behaviour living inside `Transform.iter_from_name` made this slightly hacky, but it's not _too_ bad I think -- just pass it a flag indicating whether you want the old behaviour where the path is derived relative to TRANSFORMS_DIR, or just take the path as-is. Then the list function uses the flag to set paths relative to itself rather than TRANSFORMS_DIR.
=> Make transforms in lists relative to list path, not TRANSFORMS_DIR

sheet_to_triples/trans.py
Because I was _too efficient_ and merged in before I read the additional feedback.
=> Tweak to path logic - `is None` rather than `not base_path`.

sheet_to_triples/field.py, sheet_to_triples/tests/test_xl.py, sheet_to_triples/xl.py
There's a minor hack on `field.Row` to make the `fields` attribute public as otherwise there's not a great way of extracting values from a `Row` for test comparison that doesn't rely on `Row` functionality.
=> Add tests for xl module (and by extension xls and xlsx modules).

.coveragerc, sheet_to_triples/__main__.py, sheet_to_triples/tests/test_main.py
Some not great hacks in here, all in the name of getting the coverage up to 95%.
Re: .coveragerc, I've excluded csv.py because it's not hooked into __main__ at any point and debug.py because, well, it's debug code.
=> Add unittests for __main__. Also add .coveragerc file.

sheet_to_triples/tests/test_main.py, sheet_to_triples/tests/test_trans.py
Fixes https://app.productive.io/15481-visual-meaning/projects/130026/tasks/task/1725401?filter=LTE%3D.
Wrapping everything in `os.path.normpath` is a bit of an ugly spelling, but does the job.
=> Fix unittest expected paths when run on Windows.

README.md, sheet_to_triples/field.py, sheet_to_triples/run.py, sheet_to_triples/tests/test_trans.py, sheet_to_triples/trans.py
For now list of columns in sheet must still be exhaustive, but avoid
repeating triples lines for each column in this case. Also add
conditional that allows for logic on the cell contents but can give
column name as the result value.
=> Add cross_cols for applying logic per row and col

sheet_to_triples/__main__.py
The fallback behaviour to show the input model now triggers only if
neither --add-graph nor any transform are supplied.
=> Save model after adding another graph

Makefile, sheet_to_triples/rdf.py, sheet_to_triples/tests/test_rdf.py, sheet_to_triples/tests/test_trans.py, sheet_to_triples/trans.py
General cleanup of identifier and qname parsing, by passing graph
namespace manager logic down to the functions that want to use
resolution of prefixes to namespaces.
Wrap up Formatter class and namespace handling for transforms in
`_Converter` class which adopts the `_as_*()` functions.
Drive by Makefile poke.
=> Handle namespace bindings more sensibly

sheet_to_triples/rdf.py, sheet_to_triples/tests/test_rdf.py
If the result would just be duplicated data, only notify when
`--verbose` flag is given, but always notify if the triple is not an
exact match.
=> More useful printing of non-unique triples

sheet_to_triples/field.py, sheet_to_triples/tests/test_field.py
From as_type_prefix - still special case hack, but a slightly more
useful one given it no longer dictates the whole qname prefix.
=> Change field attribute to as_type_slug

pyproject.toml, sheet_to_triples/rdf.py, sheet_to_triples/run.py, sheet_to_triples/tests/test_rdf.py
Some small incompatibilities to resolve, but get to remove version
pinning for the pyparsing dependency as well.
The work-around for incomplete FOAF namespace is no longer required,
test added to demonstrate that.
=> Update rdflib to version 6

pyproject.toml, sheet_to_triples/field.py
Using argparse features that require Python 3.8 or later, so update
`pyproject.toml` to reflect that fact.
Also change use of `functools.lru_cache()` to not evict, which in
earlier versions was the preferred spelling anyway.
=> Declare minimum Python version to be 3.8

sheet_to_triples/rdf.py
From a user point of view interacting with this project via the CLI, it does exactly what we want in a nice, low-friction manner. Translating labels which are attached to `vm:Stakeholder`, say, simply requires us to preassemble the data model as step one, as we usually do, and then in step two:
```
python -m sheet_to_triples labels_transform --model model_in.json --model-out model_out.json --translate-labels "vm:Stakeholder" --base-language en
```
And it will automatically try and match Stakeholders it finds in the data model to associated labels, and then use any translated Stakeholder data to translate the labels. 
That is all fine. Unfortunately under the hood this is a _bad_ piece of code (except for the SPARQL, which I'm quite proud of) that relies on too many operations that are 90% …
=> First pass at automatic translation of label data.

sheet_to_triples/rdf.py, sheet_to_triples/tests/test_rdf.py
Conversion of Blank Nodes from the graph to the model is a one-way operation as we cast them to string, and when the model gets converted back into a graph a string-converted Blank Node will just come out as an `rdflib.Literal`, losing the meaning. 
Further, since the purpose of this module is to convert RDF graphs into JSON that our platform can consume, and the platform has no concept of what a blank node is, this is effectively junk data. So exclude any triples containing blank nodes at the point of converting from the graph to the model.
=> When updating the model from the graph, exclude blank nodes.

README.md, sheet_to_triples/field.py, sheet_to_triples/tests/test_field.py, sheet_to_triples/tests/test_trans.py, sheet_to_triples/trans.py
Required change for https://app.productive.io/15481-visual-meaning/projects/130026/tasks/task/2323091?filter=MTEyNDM2.
- Add `conds` field to transform properties. This is a tuple containing three objects:
- A conditional evaluating to True or False, using `field.Cell` properties.
- Value if True
- Value if False
- Remove `field.ConditionCell` and replace with `exists` and `not_exists` properties on `field.Cell`.
- Redo `_cross_cols` into `melt_cols`, with associated behaviour changes in `transform.Transform.process` and `field.Row`.
- Many additional inbuilt methods for `field.Row` - `__contains__, `__setitem__`, `__eq__`.
I haven't updated the Readme yet as I'm leaving that for after the code changes are approved.
=> Redo row melting, and add conditional fields and properties

sheet_to_triples/field.py, sheet_to_triples/tests/test_field.py, sheet_to_triples/tests/test_trans.py, sheet_to_triples/trans.py
Two bugs:
- Resolving a condition in a transform will produce an `rdf.Literal("True")` or `rdf.Literal("False")` value. This will always evaluate to True, so it needs to be cast to string and then checked against the literal string value `"True"`. It's a bit of a nasty solution but works as a stopgap to get this code working.
- Rows parsed from Excel workbooks with empty columns still have `{'colname': None}` entries in the `fields` dict, so checking for the existence of the  column name is not enough when we're interested in _populated_ columns. Check for both column presence and then a column value in the `disjoint` operation.
=> Some quick fixes for bugs in the `row.melt` code.

sheet_to_triples/field.py, sheet_to_triples/tests/test_field.py
These changes were required to ingest the LECM data. `must_exist` is useful for including/omitting rows based on a cell being populated or not.
=> Add `as_rag_category` and `must_exist` fields.

sheet_to_triples/run.py, sheet_to_triples/tests/test_main.py, sheet_to_triples/tests/test_run.py
Slightly odd thing where you have to pass in a `set()` to most of the tests in order to override the default, but not too painful in the end.
`ClassOfInterest` I'm still not happy with, but I don't think we're going to come up with a better term that everyone agrees with. It at least partially sums up what we're trying to capture here.
One concern I just thought of is that this is is a public repo and it's the first time we've coded actual business logic into this - this may not be the right approach.
=> Default non_uniques and ability to pass in non_uniques to Runner

sheet_to_triples/tests/test_main.py
I pushed a small change to https://github.com/VisualMeaning/sheet-to-triples/pull/111 and then merged it without waiting for the lint checks to finish and it turns out there was an error. I have brought grave dishonor upon my house this day.
=> Fix linting bug

sheet_to_triples/field.py, sheet_to_triples/tests/test_field.py
Tweak sluggification logic to make slightly nicer slugs. Strip leading
and trailing non-word character replacements, and force 'and' spacing.
Add some more tests showing expected transformations.
=> Tidy up some as_slug edge cases

requirements.txt, sheet_to_triples/__main__.py, sheet_to_triples/read_csv.py, sheet_to_triples/run.py, sheet_to_triples/tests/test_run.py, sheet_to_triples/trans.py, sheet_to_triples/xl.py, sheet_to_triples/xls.py, sheet_to_triples/xlsx.py
This only applies to csv files and does nothing to excel files. The default decoding for csv files is `utf-8`, `sheet-encoding` allows providing other decoding options like `cp1252`.
=> Add argument sheet-encoding for decoding csv files

sheet_to_triples/run.py, sheet_to_triples/tests/test_run.py
Just wrap in a containing dict in that case on loading.
Also do a bit more validation and raise an error if the model looks unlikely.
=> Support loading terms only as model

sheet_to_triples/__main__.py
Currently a non-existent path gets past this point and blows up mysteriously later.
=> Throw if book path does not exist

Makefile, pyproject.toml
Lint using ruff which is fast and can fix some issues, though is currently still missing a few pycodestyle rules.
Add `make fix` command for easier lint addressing.
Add `make install` for dependencies with poetry and `make all`.
=> Switch to ruff for lint checking and more make

.github/workflows/gate.yml, pyproject.toml, requirements.txt
`rdflib 7.0.0` is the newest package version, which also requires python>=3.8. Updating both rdflib + python.
=> Version bump rdflib + python

sheet_to_triples/tests/test_xl.py, sheet_to_triples/xlsx.py
The unescape method parses every `_x----_` substring into ASCIII but amongst those, [some are not allowed](https://foss.heptapod.net/openpyxl/openpyxl/-/blob/branch/3.1/openpyxl/cell/cell.py#L164) in the setter.
=> Removed illegal characters.

pyproject.toml
This is the last version that doesn't sometimes break when used on workbooks containing filters.
=> Pin openpyxl to 3.0.10

pyproject.toml, sheet_to_triples/rdf.py, sheet_to_triples/tests/test_rdf.py, sheet_to_triples/trans.py
The rationale for this is somewhat long and complicated and summarised in https://github.com/VisualMeaning/map-tools/pull/97. The tl;dr is: we want to add handling for the `gist` namespace, which starts with `https` rather than `http`, and under the current `from_identifier` implementation this leads to some undesirable behaviour as it tries to serialise every single URL it sees in an object value as a `URIRef`. We need to _only_ do this for URLs which are actually IRIs, and the best metric we have for this is "does this URL string match any of our graph namespaces", which means `from_identifier` needs access to the graph whenever it's called. Hence the rewrite with `from_identifier` as a method on a `Resolver` class that's initialised with the graph.
Also actually add handling for the …
=> Make Resolver class and make from_identifier a class method

pyproject.toml
We'd like to install this repo as a package so that other projects can use the rdf parsing code. This requires some changes to pyproject.toml to make setuptools work according to [PEP 621](https://peps.python.org/pep-0621/).
Follow-on work from [SMP-2152](https://visual-meaning.atlassian.net/browse/SMP-2152).
[SMP-2152]: https://visual-meaning.atlassian.net/browse/SMP-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update pyproject.toml so that we can pip install sheet_to_triples as a package via setuptools

sheet_to_triples/rdf.py, sheet_to_triples/tests/test_rdf.py
We have a use case where `--verbose` is used to pipe the graph-as-.ttl stdout to a file. This includes all stdout output, not just the graph .ttl, which means our log lines for dropping duplicate triples are also included in this file. The log line starts with a comment character so most of the time we just get a big bunch of commented out stuff at the start of the file and it's not a problem. However, object Literals consisting of multiline strings are printed as multiple lines, and the subsequent lines after the first are *not* commented, and the file breaks.
Therefore, when printing these log lines detect when the object is an `rdflib.term.Literal`, and if it is insert additional comment characters. 
[JIRA ticket](https://visual-meaning.atlassian.net/browse/SMP-2208)
=> Comment out multi-line literals when printing with `--verbose`

sheet_to_triples/__main__.py, sheet_to_triples/rdf.py, sheet_to_triples/run.py, sheet_to_triples/tests/test_rdf.py, sheet_to_triples/tests/test_run.py
We typically create our models over two passes, once to create a model from Excel data, and then a second one to add in labels triples. Since we currently drop the oldest triple where duplicates are found, this means that the labels triples always "win" - however, we usually treat our Excel data as a source of truth so it's these older triples that should be retained.
So, add option to select behaviour when dropping duplicates. Default is the existing `keep-newest` behaviour as this is appropriate when building the Excel model itself, but allow `keep-oldest` instead at the user's discretion.
=> DRAFT: Add option to keep oldest triples when dropping duplicates

sheet_to_triples/__main__.py, sheet_to_triples/rdf.py, sheet_to_triples/run.py, sheet_to_triples/tests/test_main.py, sheet_to_triples/tests/test_rdf.py, sheet_to_triples/tests/test_run.py
This has come up a couple of times: previously we weren't regularly using ontologies in our projects, so we had to define non-unique predicates at the transform level. Now that we *are* using ontologies, we can define how we handle predicates at the ontology level.
This change adds a flag `--use-ontology-normalisation`. If the flag is passed, all predicates are assumed non-unique by default. All `non_unique` parameters will be ignored. During normalisation, we search through the model to find subject IRIs which are of type `owl:FunctionalProperty` - the [OWL definition](https://www.w3.org/TR/owl-ref/#FunctionalProperty-def) for this states that Functional Properties may only have a single value - or in other words, it is a unique predicate.
We then use our set of FunctionalProperties to …
=> Allow handling of unique predicates to be defined by ontology

sheet_to_triples/field.py, sheet_to_triples/tests/test_field.py, sheet_to_triples/tests/test_trans.py, sheet_to_triples/trans.py
- Treat whitespace-only strings as False when checking for a `.exists` condition.
- Do not attempt to template conditional values before first evaluating the condition and selecting the appropriate value to template.
=> Improved conditional handling

.github/workflows/gate.yml, sheet_to_triples/rdf.py, sheet_to_triples/tests/test_rdf.py
A user reported that the `--use-ontology-normalisation` parameter in sheet-to-triples was not deduping `owl:FunctionalProperties` at all. 
The offending line of code is fixed as part of this PR.
`t['pred']` and `t['obj']` are the predicate and object IRIs/values as pulled out of the model JSON via `json.load`. This means that they are strings. `rdf['type']` and `owl['FunctionalProperty']` are derived from `rdflib.Namespace` and are therefore `rdflib` constructs (I think `URIRef`). This means that they are not strings.
Therefore this comparison will never be true, and the list of Functional Properties for deduping will always be empty.
To fix, cast the `rdflib` bits to string during comparison.
[SMP-3205](https://visual-meaning.atlassian.net/browse/SMP-3205)
[SMP-3205]: …
=> Use strings for comparison against model terms

.github/workflows/gate.yml, README.md, pyproject.toml
The relevant poetry 2 breaking changes are all to do with how the `pyproject.toml` is formatted:
- It uses the `[project]` block properly now as per PEP 621, resolving a long-standing complaint we've had (see deleted comment).
- This means we don't need the separate `[tool.poetry]` block any more.
- However, it's very specific about what it allows to have in its `license` fields, hence the splitting of the existing `license` field into `license` and `license-files`.
- It doesn't have a specific concept of dev dependencies any more, instead making those a generic group of sub-requirements.
Additionally, when running the unittests after these changes, `pyfakefs` went completely bonkers with some kind of infinite recursion bug, so a version bump was necessary in order to fix that.
I've …
=> Update pyproject.toml to be compatible with poetry 2

pyproject.toml
`openpyxl` has been pinned in `sheet-to-triples` because of a bug. This bug seems to be no longer active.
This PR proposes to release `openpyxl`'s version to '^3.1.5'.
Verifying the bug:
- In an Excel export file, format a sheet as a table
- Activate dynamic filters
- Save
- Run the corresponding job file (upload_commands from illustrator-to-smp)
Review requested from: @VisualMeaning/devs
JIRA Ticket: [SMP-3267](https://visual-meaning.atlassian.net/browse/SMP-3267)
[SMP-3267]: https://visual-meaning.atlassian.net/browse/SMP-3267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Unpinning `openpyxl` to ^3.1.5
